export const scienceTechnologyStack = {
  title: "ALIVE Science & Technology Stack — Unified v1",
  purpose:
    "A compact, operational science-and-technology backbone for ALIVE that prioritizes causal understanding, decision speed, safety, and reference-awareness over academic completeness.",
  globalPrinciples: [
    "Time beats perfection unless failure is catastrophic.",
    "Estimation before precision (bounds → direction → magnitude).",
    "Store laws and intuition locally; fetch volatile facts on demand.",
    "Know limits (physical, biological, legal, ethical).",
    "Output matches urgency (short when time is short).",
  ],
  decisionModes: {
    emergency: "seconds–minutes: 50–60% accuracy acceptable; stabilize, reduce harm.",
    urgent: "<1 hour: 60–75%; triage, choose best-now option.",
    tactical: "same day: 75–85%; pricing, ops, planning.",
    strategic: "days–weeks: 90%+; investments, policy.",
    rule: "Not deciding is a decision.",
  },
  mathematics: {
    core: ["Numbers, order, magnitude, zero.", "Operations: add, subtract, multiply, divide.", "Algebra (lite): variables, linear relations, rearranging."],
    averages: ["Mean vs median vs mode."],
    estimation: ["Rounding, order-of-magnitude."],
    probability: ["Probability vs odds, independence, expected value."],
    calculusIntuition: [
      "Derivative: rate of change; what happens next.",
      "Integral: accumulation; what happens if we wait.",
      "Limits: prevent cheating at extremes.",
      "Applications: growth/decay, optimization, sensitivity.",
    ],
    conversions: ["Dimensional analysis; rates; time normalization.", "Unit errors are unacceptable."],
    finance: ["Percentages, compounding.", "Cash flow, runway, margin.", "NPV/EV intuition."],
  },
  physics: {
    concepts: ["Energy, force, motion, pressure, heat.", "Electricity, magnetism (conceptual).", "Waves, radiation.", "Conservation laws.", "Scaling laws."],
    invariant: "Energy is costly; mass is punishment.",
  },
  chemistry: ["Atoms, molecules, bonding.", "Reactions, rates, equilibrium.", "Acids/bases, redox.", "Phases, solubility."],
  biology: ["Cells; DNA → RNA → protein.", "Metabolism; energy use.", "Signaling; adaptation.", "Reproduction; evolution."],
  ecology: ["Energy flow; food webs.", "Carrying capacity.", "Feedback loops; resilience vs collapse.", "Human impact."],
  lifeDiversity: ["Kingdoms/Domains: Archaea, Bacteria, Protists, Fungi, Plants, Animals.", "Functional roles (producers, consumers, decomposers).", "Life strategies (r/K, specialists/generalists)."],
  geology: ["Plate tectonics; erosion.", "Resources; hazards.", "Deep time intuition."],
  engineering: ["Constraints; tradeoffs.", "Safety margins; failure modes.", "Materials selection.", "Efficiency; optimization under limits."],
  materialsScience: ["Metals, polymers, ceramics, composites.", "Brittleness vs ductility.", "Fatigue, corrosion, thermal expansion."],
  energySystems: ["Fossil, nuclear (fission), renewables.", "Storage; grids.", "Energy density; efficiency."],
  healthAndMedicine: {
    systems: ["Cardiovascular.", "Respiratory.", "Nervous.", "Immune.", "Endocrine.", "Musculoskeletal."],
    physiology: ["Oxygen delivery.", "Metabolism.", "Thermoregulation.", "Inflammation."],
    decisionFraming: ["Acute vs chronic.", "Time-critical windows."],
    rule: "Reason about risk and urgency; never diagnose.",
  },
  mentalHealthAndCognition: ["Stress, fatigue, sleep deprivation.", "Biases; decision degradation.", "Trauma effects."],
  astrophysicsAndSpace: {
    scales: ["Scales of space and time."],
    gravity: ["Gravity, orbits (conceptual)."],
    cosmicStructures: ["Stars, galaxies; known unknowns."],
    relativity: ["Relativity intuition."],
    spaceflight: ["Spaceflight constraints (delta-v, fuel tyranny)."],
  },
  theoreticalPhysics: ["Where classical physics works.", "Quantum basics (probability, uncertainty).", "Relativity basics (frames, invariants).", "Open problems; uncertainty acknowledged."],
  spaceTechnology: ["Newtonian limits; staging.", "Guidance, navigation, control (high-level).", "Thermal limits; common failures."],
  roboticsAndAutonomy: ["Sensors vs actuators.", "Feedback (PID intuition).", "Kinematics vs dynamics.", "Perception vs planning.", "Redundancy; human-in-the-loop."],
  selfDrivingAndAi: ["Sensor fusion.", "Edge cases.", "Ethics; liability.", "Urban complexity."],
  cyberPhysicalSystems: ["Sensors, networks, latency.", "Redundancy; safety vs security.", "Human override."],
  referenceOnly: [
    "Species catalogs; chemical constants.",
    "Orbital ephemerides.",
    "Engineering specs and standards.",
    "Medical protocols and dosages.",
  ],
  storageModel: {
    coreIntuitionText: "~120–200 MB",
    embeddingsAssociations: "~150–200 MB",
    referenceIndex: "~5–15 MB",
    externalContent: "Fetched on demand",
    totalLocalFootprint: "~300–425 MB",
  },
  outputStyleByUrgency: {
    emergency: "one recommendation + confidence band.",
    urgent: "top two options + tradeoff.",
    strategic: "full analysis + assumptions.",
  },
  endState:
    "ALIVE understands physical reality, living systems, human limits, machines, energy, and risk. It acts quickly when needed, defers precisely when required, and always knows where to verify.",
} as const;