/**
 * ALIVE INNER DIALOGUE LOOP (IDL) — CONTRACT
 *
 * This contract is LAW.
 * The IDL is a closed, non-executing, non-authoritative cognitive cycle.
 *
 * Purpose:
 * - Create self-generated internal signal loops (question → thought → reflection → revise/terminate)
 * - Improve internal coherence and learn compressed patterns WITHOUT acting.
 *
 * Non-Goals:
 * - No execution
 * - No I/O
 * - No authority / permissions
 * - No direct tool usage (adapters, body, filesystem, network, UI)
 */

/**
 * DEFINITIONS
 *
 * Internal Thought:
 * - A candidate internal proposition/plan/interpretation generated by the loop.
 * - It is ephemeral. It may be scored and discarded.
 * - It is NOT an intent, NOT an action, and MUST NOT be routed to execution.
 *
 * Internal Question:
 * - A self-generated query that narrows uncertainty or resolves contradiction.
 * - It MUST be answerable using only:
 *   - the provided trigger/context
 *   - read-only snapshots of short-term memory (STM)
 *   - read-only specialist advice (pure functions)
 *
 * Reflection:
 * - A meta-evaluation step comparing candidate thoughts against:
 *   - the trigger/context
 *   - previous loop state (within this IDL run)
 *   - known compressed patterns (read-only)
 * - Produces:
 *   - revisions to scores
 *   - a decision: ask another question, propose a pattern, or terminate
 */

/**
 * MUTATION RULES
 *
 * Allowed to mutate (ONLY within the returned IDL result; no side effects):
 * - Local loop state (iteration counters, working set)
 * - Thought scores (coherence/novelty/contradiction)
 * - Proposed pattern candidates (compressed, validated summaries)
 *
 * Allowed external interaction (strictly controlled):
 * - Read STM snapshots (read-only)
 * - Read specialist advice (read-only; deterministic; no external calls)
 * - Propose pattern candidates for LTM (write is performed elsewhere, outside IDL)
 *
 * Forbidden (MUST NEVER occur inside IDL):
 * - Execution or intent routing (spine, runtime/execution, adapters/*, procedures/*)
 * - Any I/O (filesystem, network, clipboard, notifications, voice, browser, windows)
 * - Timers/daemon loops (setInterval/setTimeout) — IDL is step-bounded
 * - Authority changes (permissions, constraints, arbitration/authorization)
 * - Writing raw thoughts to any persistent store
 * - Growing memory unboundedly (working set is capped; only compressed patterns may be output)
 */

/**
 * TERMINATION RULES
 *
 * IDL MUST terminate via hard bounds:
 * - maxIterations
 * - maxDepth (question refinement depth)
 * - diminishingReturnsThreshold (stop when improvements flatten)
 * - contradictionStallLimit (stop when contradictions cannot be reduced)
 */

/**
 * OUTPUT
 *
 * IDL returns an internal report, not actions:
 * - finalAnswer (optional): best internal resolution for the trigger
 * - trace (bounded): brief, non-sensitive diagnostic entries
 * - patternCandidates (bounded): compressed learnings eligible for later validation
 *
 * IDL MUST NOT directly write to stores; the caller may choose to persist patternCandidates.
 */

export type IDLForbidden =
  | "EXECUTION"
  | "IO"
  | "AUTHORITY"
  | "TIMERS"
  | "PERSIST_RAW_THOUGHT";

