// procedures/generateDemoSite.js
//
// Procedure: Generate static demo website from experience.
// Deterministic, read-only from experience, file-output only.
//
// Writes: demo/index.html

import fs from "node:fs";
import path from "node:path";

import { buildWakeNarrative } from "../runtime/wakeNarrative.js";
import { loadAllEvents } from "../experience/stream.js";

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    return true;
  }
  return false;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function compactJson(value, maxLen = 220) {
  let s;
  try {
    s = JSON.stringify(value);
  } catch {
    s = "{\"error\":\"unstringifiable\"}";
  }
  if (s.length > maxLen) return s.slice(0, maxLen) + "…";
  return s;
}

function findLastProcedureExecuted(events) {
  for (let i = events.length - 1; i >= 0; i--) {
    const e = events[i];
    if (e && e.type === "procedure_executed") return e;
  }
  return null;
}

function formatIso(ts) {
  if (!ts) return "";
  try {
    return new Date(ts).toISOString();
  } catch {
    return String(ts);
  }
}

function buildHtml({ generatedAt, wakeLine, lastAction, lastEvents }) {
  const lastActionHtml = lastAction
    ? `
      <div><strong>Procedure:</strong> ${escapeHtml(lastAction.payload?.procedureId || "")}</div>
      <div><strong>Intent:</strong> ${escapeHtml(lastAction.payload?.intent || "")}</div>
      <div><strong>Timestamp:</strong> ${escapeHtml(formatIso(lastAction.timestamp))}</div>
      <div><strong>Result:</strong> <code>${escapeHtml(compactJson(lastAction.payload?.result))}</code></div>
    `
    : `<div>No procedures have been executed yet.</div>`;

  const eventRows = lastEvents.length
    ? lastEvents.map(e => {
      const intent = e?.payload?.intent ?? "";
      return `
        <tr>
          <td>${escapeHtml(formatIso(e.timestamp))}</td>
          <td>${escapeHtml(e.type || "")}</td>
          <td>${escapeHtml(intent)}</td>
          <td><code>${escapeHtml(compactJson(e.payload))}</code></td>
        </tr>
      `;
    }).join("")
    : `<tr><td colspan="4">No events.</td></tr>`;

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ALIVE Core — Live Demo</title>
  </head>
  <body style="font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial; line-height: 1.4; padding: 24px;">
    <h1>ALIVE Core — Live Demo</h1>

    <h2>Wake Narrative</h2>
    <p>${escapeHtml(wakeLine)}</p>

    <h2>Last Action Summary</h2>
    ${lastActionHtml}

    <h2>Event Log (last ${lastEvents.length} events)</h2>
    <table border="1" cellspacing="0" cellpadding="8" style="border-collapse: collapse; width: 100%;">
      <thead>
        <tr>
          <th>Timestamp</th>
          <th>Type</th>
          <th>Intent</th>
          <th>Payload (trimmed)</th>
        </tr>
      </thead>
      <tbody>
        ${eventRows}
      </tbody>
    </table>

    <hr />
    <footer>Generated by ALIVE Core at ${escapeHtml(new Date(generatedAt).toISOString())}</footer>
  </body>
</html>`;
}

export const generateDemoSiteProcedure = {
  id: "proc_generate_demo_site",
  intent: "generate_demo_site",
  required_capabilities: ["filesystem.write", "filesystem.ensureDir"],

  steps: [
    { id: "load_experience", action: "experience.load_all" },
    { id: "build_html", action: "output.build_html" },
    { id: "ensure_dir", action: "filesystem.ensure_dir" },
    { id: "write_file", action: "filesystem.write" },
  ],

  execute({ capabilities } = {}) {
    if (!capabilities || typeof capabilities.isAvailable !== "function") {
      throw new Error("procedure requires capabilities.isAvailable(id)");
    }
    if (!capabilities.isAvailable("filesystem.ensureDir")) throw new Error("missing capability: filesystem.ensureDir");
    if (!capabilities.isAvailable("filesystem.write")) throw new Error("missing capability: filesystem.write");

    // experience/stream requires recorder to be initialized.
    // This procedure is runtime-driven; we fail loudly if it isn't.
    const events = loadAllEvents();
    const wakeLine = buildWakeNarrative(events);

    const lastAction = findLastProcedureExecuted(events);
    const lastEvents = events.slice(-5);

    const generatedAt = Date.now();
    const html = buildHtml({ generatedAt, wakeLine, lastAction, lastEvents });

    const demoDir = path.resolve(process.cwd(), "demo");
    ensureDir(demoDir);

    const page = path.join(demoDir, "index.html");
    fs.writeFileSync(page, html, "utf8");

    return {
      page: "demo/index.html",
      eventsIncluded: lastEvents.length,
      generatedAt,
    };
  },
};
